### ISSUE TITLE
Showing in User lister but it doesn't do anything

### ISSUE THREAD

**Issue by adrianbj** [Toutouwai/AddImageUrls#3]
Hi @Toutouwai - I just noticed that the textarea field for pasting URLs is appearing when viewing the Users lister, if you have an image field for users and have it selected to be displayed eg:

![image](https://user-images.githubusercontent.com/871211/119718154-11af6080-be1c-11eb-8d65-7346f9c15051.png)

I don't really think it should appear here because it doesn't work and even if it did, I don't think it makes sense as a UI.

Thanks!

**Comment by Toutouwai** [comment]
Thanks, should be fixed in v0.2.3

**Comment by adrianbj** [comment]
Thank you!
