### ISSUE TITLE
PHP Warning: copy(/xxx/site/assets/cache/WireTempDir/.AddImageUrls/0/): failed to open stream: Is a directory in /xxx/site/modules/AddImageUrls/AddImageUrls.module:184

### ISSUE THREAD

**Issue by adrianbj** [Toutouwai/AddImageUrls#4]
Hi @Toutouwai - I have a feeling this is a PW core issue, but wanted to see if you've come across it before. I've had issues with using PW's WireTempDir in the past and ended up going with PHP's system temp dir, or just using the root of assets/files and handling the cleanup myself.

**Comment by Toutouwai** [comment]
I haven't seen that before, but I don't use this module all that often. Is it reproducible with some particular image or by following particular steps?

**Comment by adrianbj** [comment]
Sorry, initially I saw this logged via Tracy when a client was making site edits so I didn't know the exact scenario. I just tested with a URL that doesn't point to an image, eg `https://google.com/` and I get that error, along with `PHP Warning: Undefined array key "path" in .../modules/AddImageUrls/AddImageUrls.module:171`

So I think that's the issue. Make sense?

**Comment by Toutouwai** [comment]
Thanks. I've added some more error checking for bad URLs in v0.2.4.

While I've got you, did you see my topic in the Tracy subforum? https://processwire.com/talk/topic/25564-automatic-maintenance-of-logs-and-exception-files/
I figure you're busy and will reply later, but just wanted to check that it didn't slip by you completely.

**Comment by adrianbj** [comment]
Thanks @Toutouwai - looks good now.

Yes, I have seen your request. Sorry I've got a few outstanding things to do on Tracy at the moment (mostly for you). I just haven't had the time at the moment - just focusing on bug reports for my modules, rather than new features at the moment, but I will try as soon as I have the bandwidth for it.

**Comment by Toutouwai** [comment]
All good, and no hurry.
