### ISSUE TITLE
Issue when using this in a repeater

### ISSUE THREAD

**Issue by andoro** [Toutouwai/AddImageUrls#6]
Dear Toutouwai,

I tried to use it when an image field was added to a repeater along with other fields with text type.
The symtoms are the following: when I enter all the text type fields data and also paste an outer image using your module, only the image is set after save, all the other fields data are lost. Comparing to a default inbuilt image upload, that one is using ajax to upload selected image before I push save, so when I save the page the other text field's data are also saved - it works as expected.
I could imagine a solution for you module in these cases, for example what if we could save and upload the inserted URLs with a button which belongs to image upload only? This way we won't use the Page save button and the images can be saved independently.

What do you think?

**Comment by Toutouwai** [comment]
Thanks for the report. Should be fixed in v0.2.6.
