### ISSUE TITLE
URL may not return an image

### ISSUE THREAD

**Issue by romaincazier** [Toutouwai/AddImageUrls#7]
Hi @Toutouwai,

I'm facing an issue where the url contains a valid extension but the returned "image" is actually a html file (because of a redirection due to the non-existence of the remote image).

I wonder if your module shouldn’t download in the [temp directory in all cases](https://github.com/Toutouwai/AddImageUrls/blob/470f9715cf516274318105c4f667a49817ef9c34/AddImageUrls.module#L255) to check the mime type of the file? I wonder if it would also avoid the download of "fake jpgs" (.psd but named with .jpg).

I could go ahead and do a PR if you want.

**Comment by Toutouwai** [comment]
That's a good idea, thanks. I have added this in v0.2.7

**Comment by romaincazier** [comment]
Amazing, thanks!
