### ISSUE TITLE
Feature request: option to show URL input without toggle button

### ISSUE THREAD

**Issue by andoro** [Toutouwai/AddImageUrls#8]
Hello,

Thanks for your module, I'm using it very effectively.
I'm uploading a lot of content, and especially when migrating content from another site, I only use image urls to do it, it's much faster.
Would be nice to have an option regarding to show always the URL input, so Paste URLs button wouldn't be necessary to click all the time. What do you think?

**Comment by Toutouwai** [comment]
I've added a config option for this in v0.3.2
